package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.45

import (
	"context"
	"example/graph/model"
)

// Test is the resolver for the test field.
func (r *queryResolver) Test(ctx context.Context, filter *model.TestFilter, a int, b int) (int, error) {
	return 666, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
