// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Query struct {
}

type TestFilter struct {
	A *TestSubFilter `json:"a,omitempty"`
	B *TestSubFilter `json:"b,omitempty"`
}

type TestSubFilter struct {
	A *string `json:"a,omitempty"`
	B *string `json:"b,omitempty"`
}
